using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WindControllerDropDown : MonoBehaviour
{
    public GameObject WindControllerPanel, AutoGeneratedPanel;

    public void SelectPanel(int val)
    {
        if (val == 0)
        {
            WindControllerPanel.transform.gameObject.SetActive(true);
            AutoGeneratedPanel.transform.gameObject.SetActive(false);
            WindArea.AutoWind = false;
        }

        if (val == 1)
        {
            WindControllerPanel.transform.gameObject.SetActive(false);
            AutoGeneratedPanel.transform.gameObject.SetActive(true);
            WindArea.AutoWind = true;
        }

    }
    void Start()
    {

    }
}
